<a href="https://colab.research.google.com/github/PercyAyimbilaNsolemna/Deep-Learning/blob/main/Broadcasting/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BROADCASTING IN PYTHON**

This notebook whaat and how broadcasting is performed in python. These concepts will be applied in caluclating gradients and cost functions in each of the neurons in the Neural Network therefore the need to familiarize ourselves with it.

In [1]:
#Import numpy as np
import numpy as np

In [2]:
#Creates a numpy 3 X 4 matrix
A = np.array([[56.0, 0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

In [4]:
#Outputs the matrix A
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
#Outputs the shape of the matrix
print(A.shape)

(3, 4)


In [6]:
#Calculates cal along columns
cal = A.sum(axis=0)

In [8]:
print(cal)

[ 59.  239.  155.4  76.9]


In [9]:
#Shape of cal
print(cal.shape)

(4,)


In [10]:
#Calculates the percentage of each cell
percentages = 100*A/cal

**EXPLANATION**

In calculating the percentages, we divide each cell in the 3*4 matrix by the corresponding cell in the 4*1 matrix. This is kindda strange, is it not supposed to shoot an error since the matrices are of different shapes??

The error is suppressed because numpy broadcasts the 4*1 matrix over the 3*4 matrix. The two matrices now turns out to be 3*4 and 4*3 matrix enabling the division operation to be performed.

An illustration on the two matrices after broadcast


A = [
      [a b c d],
      [e f g h],
      [i j k l]
]

cal = [
        [m n o p],
        [m n o p],
        [m n o p]
]


In [11]:
print(percentages)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [12]:
#Outputs the shape of the percentages matrix
print(percentages.shape)

(3, 4)
